#!/usr/bin/env fish

set -x BROWSER brave
set -x CHROME_EXECUTABLE google-chrome-stable
set -x EDITOR nvim
set -x PAGER less
set -x TERMINAL alacritty --config-file ~/.config/i3/alacritty/alacritty.toml
set -x VISUAL nvim

{%@@ if profile == "bg-city" @@%}
set -x GDK_SCALE 2
set -x QT_ENABLE_HIGHDPI_SCALING 1
{%@@ endif @@%}
